apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "vscode-web.fullname" . }}
  labels:
    app: {{ include "vscode-web.name" . }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "vscode-web.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "vscode-web.name" . }}
    spec:
      nodeSelector: {{ .Values.codeServer.nodeSelector | toJson }}
      tolerations: {{ .Values.codeServer.tolerations | toJson }}
      securityContext:
        fsGroup: 1000
      containers:
        - name: code-server
          image: ghcr.io/kloudlite/hub/coder-with-mongosh:latest
          args:
            - --auth
            - password
          workingDir: /home/coder/workspace
          env:
            - name: SERVICE_URL
              value: https://open-vsx.org/vscode/gallery
            - name: ITEM_URL
              value: https://open-vsx.org/vscode/item
            - name: PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "vscode-web.fullname" . }}-secret
                  key: password
          resources: {{ .Values.codeServer.resources | toYaml | nindent 12 }}
          volumeMounts:
            - name: storage
              mountPath: /home/coder
      volumes:
        - name: storage
          persistentVolumeClaim:
            claimName: {{ include "vscode-web.fullname" . }}-pvc 