apiVersion: v1
kind: Secret
metadata:
  name: "{{.Release.Name}}-exports"
  namespace: {{.Release.Namespace}}
type: Opaque
stringData:
  PASSWORD: {{ .Values.codeServer.password | quote }}
  URL: https://{{ .Values.codeServer.ingress.host }}