{{- if .Values.codeServer.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "vscode-web.fullname" . }}
  labels:
    app: {{ include "vscode-web.name" . }}
  {{- if .Values.codeServer.ingress.clusterIssuer }}
  annotations:
    cert-manager.io/cluster-issuer: {{ .Values.codeServer.ingress.clusterIssuer }}
  {{- end }}
spec:
  ingressClassName: {{ .Values.codeServer.ingress.className }}
  rules:
    - host: {{ .Values.codeServer.ingress.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "vscode-web.fullname" . }}
                port:
                  number: 80
  {{- if .Values.codeServer.ingress.clusterIssuer }}
  tls:
    - hosts:
        - {{ .Values.codeServer.ingress.host }}
      secretName: {{ include "vscode-web.fullname" . }}-tls
  {{- end }}
{{- end }} 