apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "vscode-web.fullname" . }}-pvc
  labels:
    app: {{ include "vscode-web.name" . }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.codeServer.storage.size }}
  storageClassName: ebs-sc-ap-south-1b