apiVersion: v1
kind: Secret
metadata:
  name: {{ include "vscode-web.fullname" . }}-secret
  labels:
    app: {{ include "vscode-web.name" . }}
type: Opaque
data:
  password: {{ .Values.codeServer.password | b64enc | quote }}