codeServer:
  repository: "https://github.com/kloudlite/website.git"
  branch: "release-v1.0.0"
  storage: 
    size: "5Gi"
    className: ""

  nodeSelector: {}
  tolerations:
  - key: small_1
    operator: "Equal"
    value: "true"
    effect: NoSchedule

  extensions: []

  resources:
    requests:
      cpu: "100m"
      memory: "150Mi"
    limits:
      cpu: "200m"
      memory: "300Mi"

  ingress:
    enabled: false
    className: nginx #updated this [regression was working fine without this change]
    clusterIssuer: "kloudlite-cert-issuer" #updated this [regression was working fine without this change]

    host: "google.com" #updated this [regression was working fine without this change]
    cors:
      enabled: false
      origins: []

mongodb:
  enabled: false
  storage:
    size: "1Gi"
    # className: ""

  nodeSelector: {}
  tolerations: []

  resources:
    requests:
      memory: 256Mi
      cpu: 250m
    limits:
      memory: 512Mi
      cpu: 500m
