controller:
  serviceType: ClusterIP
  installPlugins:
    - kubernetes:3937.vd7b_82db_e347b_
    - workflow-aggregator:590.v6a_d052e5a_a_b_5
  resources:
    requests:
      cpu: "500m"
      memory: "1Gi"
    limits:
      cpu: "1000m"
      memory: "2Gi"
  servicePort: 8080
  adminUser: "admin"
  adminPassword: "jenkins-admin"

image:
  pullPolicy: IfNotPresent

ingress:
  enabled: true
  host: "jenkins.local"
  className: "nginx"
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
  cors:
    enabled: true
    origins:
      - "http://jenkins.local"

expose:
  enabled: true
  host: ""
  port: 8080

persistence:
  enabled: true
  accessModes:
    - ReadWriteOnce
  size: 20Gi
  storageClass: "ebs-sc-ap-south-1b"
