controller:
  serviceType: NodePort
  installPlugins:
    - kubernetes:3937.vd7b_82db_e347b_
    - workflow-aggregator:590.v6a_d052e5a_a_b_5
  adminUser: admin
  adminPassword: admin123
  resources:
    requests:
      cpu: "100m"
      memory: "256Mi"
    limits:
      cpu: "200m"
      memory: "512Mi"
  servicePort: 8080

expose:
  host: ""

serviceAccount:
  name: kloudlite-cluster-admin
