{{- if .Values.configmap.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "snowflake-sandbox.fullname" . }}
  labels:
    {{- include "snowflake-sandbox.labels" . | nindent 4 }}
data:
  # Add custom config here
  # Example:
  # EXTRA_CONFIG: "value"
{{- end }} 