{{- if not .Values.externalSecrets.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.snowflake.passwordSecretRef }}
  labels:
    {{- include "snowflake-sandbox.labels" . | nindent 4 }}
type: Opaque
data:
  password: {{ .Values.snowflake.password | b64enc | quote }}
{{- else }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Values.externalSecrets.secretName }}
  labels:
    {{- include "snowflake-sandbox.labels" . | nindent 4 }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: {{ .Values.externalSecrets.secretStoreName }}
    kind: SecretStore
  target:
    name: {{ .Values.externalSecrets.secretName }}
  data:
    - secretKey: password
      remoteRef:
        key: {{ .Values.externalSecrets.remoteKey }}
        property: password
{{- end }} 