GEMINI_API_KEY: "AIzaSyDkWhz6g0gdUkni0oKrJuCmhoO32cCGBlY"

nodeSelector: {}
tolerations: []

resources:
  requests:
    cpu: "500m"
    memory: "512Mi"
  limits:
    cpu: "1000m"
    memory: "1024Mi"

storage:
  size: "1Gi"

ingress:
  enabled: true
  className: nignx
  clusterIssuer: "kloudlite-cert-issuer"
  host: ""
  cors:
    enabled: false
    origins: []
  auth:
    enabled: false
