apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-cockroachdb-config
  labels:
    app: cockroachdb
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
data:
  cockroach.conf: |
    # CockroachDB configuration
    # See https://www.cockroachlabs.com/docs/stable/configure-cockroachdb.html
    
    [server]
    http-port = {{ .Values.service.httpPort }}
    port = {{ .Values.service.grpcPort }}
    
    [security]
    mode = insecure
