apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: cockroachdb
spec:
  serviceName: cockroachdb
  replicas: 1
  selector:
    matchLabels:
      app: cockroachdb
  template:
    metadata:
      labels:
        app: cockroachdb
    spec:
      containers:
        - name: cockroachdb
          image: cockroachdb/cockroach:v24.1.0
          args: ["start-single-node", "--insecure"]
          ports:
            - containerPort: {{ .Values.service.httpPort }}
            - containerPort: {{ .Values.service.grpcPort }}
          volumeMounts:
            - name: data
              mountPath: /cockroach/cockroach-data
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 10Gi
