apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Release.Name }}-cockroachdb
  labels:
    app: cockroachdb
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
spec:
  serviceName: {{ .Release.Name }}-cockroachdb
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: cockroachdb
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: cockroachdb
        release: {{ .Release.Name }}
    spec:
      containers:
      - name: cockroachdb
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.service.grpcPort }}
          name: grpc
        - containerPort: {{ .Values.service.httpPort }}
          name: http
        command:
        - "/bin/bash"
        - "-ecx"
        - |
          # The use of qualified `hostname -f` is crucial:
          # Other nodes aren't able to look up the unqualified hostname.
          CRARGS=("start" "--insecure" "--advertise-host=$(hostname -f)" "--http-addr=0.0.0.0:{{ .Values.service.httpPort }}" "--listen-addr=0.0.0.0:{{ .Values.service.grpcPort }}" "--logtostderr=INFO" "--store=/cockroach/cockroach-data")
          
          # Join existing cluster if not first node
          if [ ! "$(hostname)" == "{{ .Release.Name }}-cockroachdb-0" ]; then
            CRARGS+=("--join={{ .Release.Name }}-cockroachdb-0.{{ .Release.Name }}-cockroachdb:{{ .Values.service.grpcPort }}")
          fi
          
          exec /cockroach/cockroach "${CRARGS[@]}"
        volumeMounts:
        - name: datadir
          mountPath: /cockroach/cockroach-data
        resources:
{{ toYaml .Values.resources | indent 10 }}
      terminationGracePeriodSeconds: 60
      affinity:
{{ toYaml .Values.affinity | indent 8 }}
      nodeSelector:
{{ toYaml .Values.nodeSelector | indent 8 }}
      tolerations:
{{ toYaml .Values.tolerations | indent 8 }}
  volumeClaimTemplates:
  {{- if .Values.persistence.enabled }}
  - metadata:
      name: datadir
    spec:
      accessModes: 
        {{- range .Values.persistence.accessModes }}
        - {{ . | quote }}
        {{- end }}
      storageClassName: {{ .Values.persistence.storageClass }}
      resources:
        requests:
          storage: {{ .Values.persistence.size }}
  {{- end }} 