apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Release.Name }}-cockroachdb-init
  labels:
    app: cockroachdb
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "5"
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    metadata:
      labels:
        app: cockroachdb-init
        release: {{ .Release.Name }}
    spec:
      containers:
      - name: cockroachdb-init
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        command: ["/bin/bash", "/scripts/init.sh"]
        volumeMounts:
        - name: init-script
          mountPath: /scripts
      volumes:
      - name: init-script
        configMap:
          name: {{ .Release.Name }}-cockroachdb-init
          defaultMode: 0755
      restartPolicy: OnFailure 