apiVersion: v2
name: vscode-web
description: A Helm chart for Kubernetes to install and manage a cloud-based VS Code web environment (no database)
type: application
version: 0.1.0
appVersion: "1.16.0" 