apiVersion: v2
name: neo4j
description: A Helm chart for Kubernetes
version: 0.1.0
appVersion: "4.4.0"




            ../../wip-charts/neo4j/chart.yaml
            ../../wip-charts/neo4j/templates/deployment.yaml
            ../../wip-charts/neo4j/templates/ingress.yaml
            ../../wip-charts/neo4j/templates/service.yaml
            ../../wip-charts/neo4j/values.yaml