version: 3

vars:
  ReleaseName: "crewai"
  ReleaseNamespace: "testing-crewai"

tasks:
  build:
    cmds:
      - helm dependency update
      - helm dependency build
  install:
    cmds:
      - helm upgrade --install {{.ReleaseName}} -n {{.ReleaseNamespace}} --create-namespace .

  template:
    cmds:
      - helm template --dry-run {{.ReleaseName}} -n {{.ReleaseNamespace}} --create-namespace .

  uninstall:
    cmds:
      - helm uninstall {{.ReleaseName}} -n {{.ReleaseNamespace}}
