ingress:
  enabled: true
<<<<<<< HEAD
  host: "cockroachdb.cloud.machinehack.com"
=======
  host: "cockroachdb.machinehack-new.clients.kloudlite.io"
>>>>>>> 92ab130aa09a534d805feb22a601a2cfd70fcca4
  className: nginx
  cors:
    enabled: false
    origins: []
  tls:
    enabled: true
    clusterIssuer: "kloudlite-cert-issuer"
  annotations: 
    cert-manager.io/cluster-issuer: kloudlite-cert-issuer

replicaCount: 1

image:
  repository: cockroachdb/cockroach
  tag: "v23.1.11"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  grpcPort: 26257
  httpPort: 8080
init:
  databases: ["defaultdb"]
  username: "root"
  password: ""

resources:
  requests:
    cpu: "500m"
    memory: "1Gi"
  limits:
    cpu: "2"
    memory: "4Gi"

nodeSelector: {}

tolerations: []

affinity:
  podAntiAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
    - weight: 100
      podAffinityTerm:
        labelSelector:
          matchExpressions:
          - key: app
            operator: In
            values:
            - cockroachdb
        topologyKey: kubernetes.io/hostname

persistence:
  enabled: false
  size: 100Gi
  storageClass: "standard"
  accessModes:
    - ReadWriteOnce
