image:
  repository: n8nio/n8n
  tag: "1.28.0"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 5678

ingress:
  enabled: true
  className: nginx
  annotations: 
    cert-manager.io/cluster-issuer: kloudlite-cert-issuer
  host: n8n.machinehack-new.clients.kloudlite.io
  paths:
    - path: /
      pathType: Prefix
  tls:
    enabled: true
    clusterIssuer: "kloudlite-cert-issuer"

replicaCount: 1
resources:
  requests:
    cpu: "250m"
    memory: "512Mi"
  limits:
    cpu: "500m"
    memory: "1Gi"

env:
  - name: N8N_PORT
    value: "5678"
  - name: N8N_PROTOCOL
    value: "http"
  - name: N8N_HOST
    value: "n8n.machinehack-new.clients.kloudlite.io"
  - name: N8N_EDITOR_BASE_URL
    value: "https://n8n.machinehack-new.clients.kloudlite.io"
  - name: N8N_BASIC_AUTH_ACTIVE
    value: "true"
  - name: N8N_BASIC_AUTH_USER
    value: "admin"
  - name: N8N_BASIC_AUTH_PASSWORD
    value: "password"
  - name: N8N_USER_MANAGEMENT_DISABLED
    value: "false"
  - name: N8N_DIAGNOSTICS_ENABLED
    value: "true"
  - name: N8N_DIAGNOSTICS_CONFIG_ENABLED
    value: "true"
  - name: N8N_LOG_LEVEL
    value: "info"
  - name: N8N_ENFORCE_SETTINGS_FILE_PERMISSION
    value: "true"
  - name: NODE_ENV
    value: "production"

nodeSelector: {}
tolerations: []
affinity: {}