ingress:
  enabled: true
  className: nginx
  path: /neo4j
  architecture: "standalone"
  tls:
    enabled: true
    clusterIssuer: "kloudlite-cert-issuer"
  cors:
    enabled: true
    origins:
      - "*"
    
  volumePermissions:
    enabled: true

  arbiter:
    enabled: false

  resources:
    requests:
      cpu: "200m"
      memory: "256Mi"
    limits:
      cpu: "400m"
      memory: "512Mi"

  nodeSelector: {}
  tolerations: []
