apiVersion: v1
kind: Secret
metadata:
  name: {{ include "github-lab.fullname" . }}-secret
  labels:
    app.kubernetes.io/name: {{ include "github-lab.name" . }}
    helm.sh/chart: {{ include "github-lab.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
data:
  githubClientId: {{ .Values.secret.githubClientId | b64enc | quote }}
  githubClientSecret: {{ .Values.secret.githubClientSecret | b64enc | quote }} 