apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-jenkins
  labels:
    app: jenkins
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: jenkins
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: jenkins
          image: "jenkins/jenkins:{{ .Values.controller.tag | default .Chart.AppVersion }}-lts-jdk11"
          imagePullPolicy: {{ .Values.image.pullPolicy | default "IfNotPresent" }}
          ports:
            - name: http
              containerPort: {{ .Values.controller.servicePort }}
            - name: agent
              containerPort: 50000
          env:
            - name: JENKINS_OPTS
              value: "--prefix=/jenkins"
            - name: JENKINS_ADMIN_ID
              valueFrom:
                secretKeyRef:
                  name: jenkins-admin-credentials
                  key: jenkins-admin-user
            - name: JENKINS_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: jenkins-admin-credentials
                  key: jenkins-admin-password
            - name: JAVA_OPTS
              value: "-Djenkins.install.runSetupWizard=false -Dhudson.model.DirectoryBrowserSupport.CSP=\"default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline';\""
          volumeMounts:
            - name: jenkins-home
              mountPath: /var/jenkins_home
            - name: jenkins-config
              mountPath: /var/jenkins_home/init.groovy.d/
          resources:
{{ toYaml .Values.controller.resources | indent 12 }}
          livenessProbe:
            httpGet:
              path: /login
              port: http
            initialDelaySeconds: 90
            timeoutSeconds: 5
            failureThreshold: 12
          readinessProbe:
            httpGet:
              path: /login
              port: http
            initialDelaySeconds: 60
            timeoutSeconds: 5
      volumes:
        - name: jenkins-home
          {{- if .Values.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-jenkins-pvc
          {{- else }}
          emptyDir: {}
          {{- end }}
        - name: jenkins-config
          configMap:
            name: {{ .Release.Name }}-jenkins-config
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
