apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-jenkins
  labels:
    app: jenkins
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
spec:
  type: {{ .Values.controller.serviceType | default "ClusterIP" }}
  ports:
    - port: {{ .Values.controller.servicePort }}
      targetPort: {{ .Values.controller.servicePort }}
      protocol: TCP
      name: http
    - port: 50000
      targetPort: 50000
      protocol: TCP
      name: agent
  selector:
    app: jenkins
    release: {{ .Release.Name }}
